/*
  Copyright 2021 Kidus Tiliksew

  This file is part of Tensor EMR.

  Tensor EMR is free software: you can redistribute it and/or modify
  it under the terms of the version 2 of GNU General Public License as published by
  the Free Software Foundation.

  Tensor EMR is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { gql } from "@apollo/client";
export var BILLINGS = gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  query Billings($page: PaginationInput!, $searchTerm: String) {\n    billings(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      edges {\n        node {\n          id\n          item\n          code\n          price\n          credit\n          remark\n        }\n      }\n      pageInfo {\n        totalPages\n      }\n    }\n  }\n"], ["\n  query Billings($page: PaginationInput!, $searchTerm: String) {\n    billings(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      edges {\n        node {\n          id\n          item\n          code\n          price\n          credit\n          remark\n        }\n      }\n      pageInfo {\n        totalPages\n      }\n    }\n  }\n"])));
export var SUPPLIES = gql(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query Supply($page: PaginationInput!, $searchTerm: String) {\n    supplies(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      edges {\n        node {\n          id\n          title\n          active\n          billings {\n            id\n            item\n            code\n          }\n        }\n      }\n      pageInfo {\n        totalPages\n      }\n    }\n  }\n"], ["\n  query Supply($page: PaginationInput!, $searchTerm: String) {\n    supplies(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      edges {\n        node {\n          id\n          title\n          active\n          billings {\n            id\n            item\n            code\n          }\n        }\n      }\n      pageInfo {\n        totalPages\n      }\n    }\n  }\n"])));
export var FIND_TODAYS_CHECKED_IN_APPOINTMENTS = gql(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  query FindTodaysCheckedInAppointments(\n    $page: PaginationInput!\n    $searchTerm: String\n  ) {\n    findTodaysCheckedInAppointments(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      pageInfo {\n        totalPages\n      }\n      edges {\n        node {\n          id\n\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n"], ["\n  query FindTodaysCheckedInAppointments(\n    $page: PaginationInput!\n    $searchTerm: String\n  ) {\n    findTodaysCheckedInAppointments(page: $page, searchTerm: $searchTerm) {\n      totalCount\n      pageInfo {\n        totalPages\n      }\n      edges {\n        node {\n          id\n\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n"])));
export var MEDICATION_PRESCRIPTIONS = gql(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  query SearchMedicalPrescriptions(\n    $page: PaginationInput!\n    $filter: MedicalPrescriptionFilter\n  ) {\n    searchMedicalPrescriptions(page: $page, filter: $filter) {\n      totalCount\n      pageInfo {\n        totalPages\n      }\n      edges {\n        node {\n          id\n          medication\n          sig\n          refill\n          generic\n          substitutionAllowed\n          directionToPatient\n          prescribedDate\n          history\n          status\n        }\n      }\n    }\n  }\n"], ["\n  query SearchMedicalPrescriptions(\n    $page: PaginationInput!\n    $filter: MedicalPrescriptionFilter\n  ) {\n    searchMedicalPrescriptions(page: $page, filter: $filter) {\n      totalCount\n      pageInfo {\n        totalPages\n      }\n      edges {\n        node {\n          id\n          medication\n          sig\n          refill\n          generic\n          substitutionAllowed\n          directionToPatient\n          prescribedDate\n          history\n          status\n        }\n      }\n    }\n  }\n"])));
export var vitalSignsFragment = gql(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  fragment VitalSignsFragment on VitalSigns {\n    id\n    temperature\n    pulse\n    bloodPressureSystolic\n    bloodPressureDiastolic\n    respiratoryRate\n    oxygenSaturation\n    height\n    weight\n    bmi\n    rightDistanceUncorrected\n    leftDistanceUncorrected\n    rightDistancePinhole\n    leftDistancePinhole\n    rightDistanceCorrected\n    leftDistanceCorrected\n    rightNearUncorrected\n    leftNearUncorrected\n    rightNearPinhole\n    leftNearPinhole\n    rightNearCorrected\n    leftNearCorrected\n    rightApplanation\n    leftApplanation\n    rightTonopen\n    leftTonopen\n    rightDigital\n    leftDigital\n    rightNoncontact\n    leftNoncontact\n  }\n"], ["\n  fragment VitalSignsFragment on VitalSigns {\n    id\n    temperature\n    pulse\n    bloodPressureSystolic\n    bloodPressureDiastolic\n    respiratoryRate\n    oxygenSaturation\n    height\n    weight\n    bmi\n    rightDistanceUncorrected\n    leftDistanceUncorrected\n    rightDistancePinhole\n    leftDistancePinhole\n    rightDistanceCorrected\n    leftDistanceCorrected\n    rightNearUncorrected\n    leftNearUncorrected\n    rightNearPinhole\n    leftNearPinhole\n    rightNearCorrected\n    leftNearCorrected\n    rightApplanation\n    leftApplanation\n    rightTonopen\n    leftTonopen\n    rightDigital\n    leftDigital\n    rightNoncontact\n    leftNoncontact\n  }\n"])));
export var SHOULD_PAY_FOR_CONSULTATION = gql(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  query ShouldPayForConsultation($patientId: ID!, $date: Time!) {\n    payForConsultation(patientId: $patientId, date: $date)\n  }\n"], ["\n  query ShouldPayForConsultation($patientId: ID!, $date: Time!) {\n    payForConsultation(patientId: $patientId, date: $date)\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
